FROM lsiobase/alpine:arm32v7-3.10

# copy local files
COPY root/ /

COPY AirConnect/bin/airupnp-arm-static /usr/local/bin/airupnp-arm

RUN chmod a+x /usr/local/bin/airupnp-arm

# ports and volumes
VOLUME /config
