name: Publish Docker image
on: workflow_dispatch
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check out the AirConnect repo
        uses: actions/checkout@v2
        with:
          repository: 'philippe44/AirConnect'
          path: 'AirConnect'
      - name: GetAirConnect version
        id: version
        run: |
          echo "::set-output name=version::$(cat AirConnect/CHANGELOG | head -1)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.armhf
          platforms: linux/arm/v7
          push: true
          tags: ghcr.io/jacaru/airupnp-image:v${{ steps.version.outputs.version }},ghcr.io/jacaru/airupnp-image:latest
